function acolher(){

document.getElementById("mensagem").innerHTML=
"Obrigado por compartilhar seus sentimentos. Lembre-se: procurar ajuda é um ato de coragem. Nenhuma informação foi armazenada.";

}

function corrigirQuiz(){

let pontos=0;

let respostas=document.querySelectorAll("input[type=radio]:checked");

respostas.forEach(function(item){

pontos+=Number(item.value);

});

document.getElementById("resultado").innerHTML=
"Você acertou "+pontos+" de 5 perguntas.";

}

function modoEscuro(){

document.body.classList.toggle("dark");

}

function aumentarFonte(){

document.body.style.fontSize="20px";

}

function topFunction(){

window.scrollTo({
top:0,
behavior:"smooth"
});

}